config/routes.rb
RailsProbe::Engine.routes.draw do
  get 'main', to: 'application#main'
  root to: 'application#index'

  resources :reports do
    collection { delete 'remove', to: 'reports#destory_all' }
    member { get 'print/:file', to: 'reports#print' }
  end
  # get 'reports', to: 'reports#index'
  # get 'reports/:id', to: 'reports#show'

  get 'listener', to: 'listener#index'
  get 'listener/on', to: 'listener#on'
  get 'listener/off', to: 'listener#off'
  get 'listener/config', to: 'listener#config'
  post 'listener/config', to: 'listener#update_config'

  get ':id', to: 'application#index'
end

app/models/rails_probe/application_record.rb
module RailsProbe
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/rails_probe/listener.rb
require 'ruby-prof'
require 'logger'

module RailsProbe
  module Listener
    extend ActiveSupport::Concern

    included do
      around_action :rails_probe_listen
    end

    def probed_event_name
      values = params.except(:controller, :action).values
      "#{params[:controller]}##{params[:action]}#{values.any? ? "(#{values.join(', ')})" : ''}"
    end

    def rails_probe_listen(&block)
      logger.info "probing..."
      if RailsProbe.listening?
        logger.warn "probed: #{probed_event_name}"
        Listener.listen(event_name: probed_event_name, session: session, request: request, user: try(:user), &block)
      else
        block.call
      end
    end

    module_function

    def listen(event_name:, session:, request:, user:, &block)
      begin
        profile = RubyProf.profile do
          block.call
        end

        ReportFactory.create(
          profile,
          action: event_name,
          session: session.try(:id),
          host: request.try(:host),
          user_id: user.try(:id),
          printers: available_printers
        )
      rescue StandardError => e
        logger.error("RailsProbe Listener broke: #{e}")
        # run call anyway (risky!)
        block.call
      end
    end

    # TODO: clean up printer mapping
    def available_printers
      printer_map = {
        graphText: Printers::GraphText.name,
        graphHtml: Printers::GraphHtml.name,
        callStack: Printers::CallStack.name
      }

      RailsProbe.printer_config.map do |printer, enabled|
        printer_map[printer.to_sym] if enabled
      end.compact
    end

    def logger
      @logger ||= Logger.new(STDOUT)
    end
  end
end

app/models/rails_probe/printer.rb
require 'ruby-prof'

module RailsProbe
  class Printer

    BASE_PATH = "#{RailsProbe::PRINTERS_DIR}/ruby_profiles"

    def self.dir
      [BASE_PATH, Rails.env].join('/')
    end

    def initialize(result, report, action)
      @result = result
      @report = report
      @action = action
    end

    # TODO: add rescue to handle failing printer
    def print
      File.open(filepath, 'w') do |f|
        printer.print(f, options)
      end
      filepath
    end

    private

    def timestamp
      @timestamp ||= DateTime.current.strftime('%Y%m%dT%H%M%S')
    end

    def output_dir
      [self.class.dir, @report.id, timestamp].join('/')
    end

    def filepath
      @filepath if @filepath
      FileUtils.mkdir_p(output_dir) unless File.exists?(output_dir)
      @filepath = "#{output_dir}/#{printer_filename}"
    end

    def options
      {}
    end

    def printer_filename
      raise NotImplementedError
    end

    def printer
      @printer ||= self.class::PRINTER.new(@result)
    end
  end
end

app/models/rails_probe/printers/call_stack.rb
module RailsProbe
  module Printers
    class CallStack < Printer
      PRINTER = RubyProf::CallStackPrinter

      def name
        'Call Stack'
      end

      private

      def options
        {
          title: title,
          print_file: true
        }
      end

      def title
        @title || name
      end

      def printer_filename
        'call_stack.html'
      end
    end
  end
end

app/models/rails_probe/printers/graph_html.rb
module RailsProbe
  module Printers
    class GraphHtml < Printer
      PRINTER = RubyProf::GraphHtmlPrinter

      def name
        'Graph HTML'
      end

      private

      def printer_filename
        'graph.html'
      end
    end
  end
end

app/models/rails_probe/printers/graph_text.rb
require 'ruby-prof'

module RailsProbe
  module Printers
    class GraphText < Printer
      PRINTER = RubyProf::GraphPrinter

      def name
        'Graph Text'
      end

      private

      def printer_filename
        'graph.txt'
      end
    end
  end
end

app/models/rails_probe/report.rb
module RailsProbe
  class Report < ActiveRecord::Base
    include ActiveModel::Serialization

    serialize :data

    before_destroy :delete_prints

    def attributes
      {
        id: nil,
        host: nil,
        session: nil,
        action: nil,
        created_at: nil,
        prints: []
      }
    end

    def print(type)
      selected_print = prints.detect { |p| p.type == type }
      selected_print.filepath
    end

    def prints
      build_prints
    end

    private

    Print = Struct.new(:name, :url, :type, :filepath)

    # Delete all the files saved for each report
    def delete_prints
      raw_prints.each { |_k, v| delete_print(v) }
    end

    def delete_print(filepath)
      File.delete(filepath) if File.exist?(filepath)
    end

    def build_prints
      @raw_prints ||= raw_prints.map do |p|
        name = p[0]
        filepath = p[1]

        type = name.try(:downcase).try(:tr, "\s", '-')
        ext  = File.extname(filepath)
        url  = "rails_probe/reports/#{id}/print/#{type}#{ext}"

        Print.new(name, url, type, filepath)
      end
    end

    def raw_prints
      (data && data[:prints]) || []
    end
  end
end

app/controllers/rails_probe/application_controller.rb
module RailsProbe
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    skip_before_action :verify_authenticity_token

    before_action :cors_preflight_check
    after_action :cors_set_access_control_headers

    def index
      render file: Engine.root.join('client', 'build', 'index.html')
    end

    def main
      respond_to do |format|
        format.js { render file: Engine.root.join('client', 'build', 'main.js') }
        format.css { render file: Engine.root.join('client', 'build', 'main.css') }
      end
    end

    private

    def cors_set_access_control_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
      headers['Access-Control-Max-Age'] = "1728000"
    end

    def cors_preflight_check
      if request.method == 'OPTIONS'
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
        headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
        headers['Access-Control-Max-Age'] = '1728000'

        render :text => '', :content_type => 'text/plain'
      end
    end
  end
end

app/controllers/rails_probe/listener_controller.rb
require_dependency "rails_probe/application_controller"

module RailsProbe
  class ListenerController < ApplicationController

    def index
      render json: { listening: listening? }, status: :accepted
    end

    def on
      render json: { listening: enable }, status: :accepted
    end

    def off
      render json: { listening: disable }, status: :accepted
    end

    def config
      render json: RailsProbe.printer_config
    end

    def update_config
      RailsProbe.printer_config = update_params
      render json: RailsProbe.printer_config
    end

    private

    def listening?
      RailsProbe.listening?
    end

    def enable
      RailsProbe.listening=true
      RailsProbe.listening?
    end

    def disable
      RailsProbe.listening=false
      RailsProbe.listening?
    end

    def update_params
      params.permit(:graphText, :graphHtml, :callStack)
    end
  end
end

app/controllers/rails_probe/reports_controller.rb
require 'pry'
require_dependency "rails_probe/application_controller"

module RailsProbe
  class ReportsController < ApplicationController
    before_action :set_report, only: [:show, :print]

    # GET /reports
    def index
      @reports = Report.all
      render json: @reports
    end

    # GET /reports/1
    def show
      @prints = @report.prints
      render json: @report
    end

    # DELETE /reports/1
    def destroy
      @report.destroy
      render json: true, notice: 'Report was successfully destroyed.'
    end

    def destory_all
      @reports = Report.all
      @reports.destroy_all
      render json: true, notice: 'Reports were successfully destroyed.'
    end

    def print
      report_print = @report.print(print_type)
      io = report_print ? File.expand_path(report_print, Rails.root) : 'No file found'
      render file: io, layout: false
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    def file
      params.permit(:file)[:file]
    end

    def print_type
      ext = File.extname(file)
      File.basename(file, ext)
    end

    # Only allow a trusted parameter "white list" through.
    def report_params
      params.require(:report).permit(:host, :session, :user_id, :action, :path)
    end
  end
end

app/helpers/rails_probe/application_helper.rb
module RailsProbe
  module ApplicationHelper
  end
end

app/helpers/rails_probe/reports_helper.rb
module RailsProbe
  module ReportsHelper
  end
end

app/views/rails_probe/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :host %>
    <%= form.text_field :host, id: :report_host %>
  </div>

  <div class="field">
    <%= form.label :session %>
    <%= form.text_field :session, id: :report_session %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :report_user_id %>
  </div>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action, id: :report_action %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path, id: :report_path %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, id: :report_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rails_probe/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/rails_probe/reports/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'rails_probe/shared/listener_toggle', toggle_path: ("/rails_probe/listener/#{RailsProbe.listening? ? 'off' : 'on'}") %>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th>Session</th>
      <th>User</th>
      <th>Action</th>
      <th>Path</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.host %></td>
        <td><%= report.session %></td>
        <td><%= report.user_id %></td>
        <td><%= report.action %></td>
        <td><%= report.path %></td>
        <td><%= report.data %></td>
        <td><%= link_to 'Show', report_path(report) %></td>
        <td><%= link_to 'Destroy', report_path(report), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/rails_probe/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/rails_probe/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @report.host %>
</p>

<p>
  <strong>Session:</strong>
  <%= @report.session %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user_id %>
</p>

<p>
  <strong>Action:</strong>
  <%= @report.action %>
</p>

<div id='tabs' class="report-text">
  <ul>
    <% @prints.each do |print| %>
      <li><a href="#<%= print.name.underscore %>"><span><%= print.name %></span></a></li>
    <% end %>
  </ul>
  <% @prints.each do |print|
%>
    <div id="<%= print.name.underscore %>">
      <iframe src="<%= print.path.gsub("#{RailsProbe::PRINTERS_DIR}\/",'/').html_safe %>"></iframe>
    </div>
  <% end %>
</div>

<p>
  <strong>Data:</strong>
  <%= @report.data %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

<style>
  .report-text {
    max-height: 45em;
    white-space: pre-wrap;
    overflow: hidden;
    border: 1px #555 solid;
    width: 940px;
    overflow-y: scroll;
  }
</style>